@printf(x: str): int
@exit(x: int)

#[primitive(type = :binary, precedence = 30)]
fc ?(a: float, b: float): bool
    if a == 1.0
        if b == 0.0
            return true
        end

        return true
    end

    return false
end



fc main
    loop i, v in "IterThroughMe"
        printf(v)
    end

    1.0 ? 0.0

    add(1.0, 0.1)
    printf("Hi\n")
end

fc add(a: float, b: float): float
    return a + b
end